# Generated by Django 4.0.6 on 2023-02-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='top_selled',
            field=models.BooleanField(default=False),
        ),
    ]
