# Generated by Django 4.0.6 on 2023-02-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('unread', 'unread'), ('viewed', 'viewed')], default='unread', max_length=20),
        ),
    ]
