# Generated by Django 4.0.6 on 2023-02-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_contact_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
