# Generated by Django 4.1.2 on 2023-02-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_cartitems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='user',
        ),
    ]
