# Generated by Django 4.0.6 on 2023-02-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_cartitems_user'),
        ('customer', '0009_remove_products_stock_products_available'),
    ]

    operations = [
    ]
